[bg storage=room.jpg time=600]
[layopt layer=0 visible=true]
[image layer=0 x=300 y=50 storage=chara/akane/normal.png time=600]
こんにちは。[l][r]
ここにスクリプトを書いてから、[r]
左上にある「再実行」をクリックするか、[r]
もしくはキーボードの「F5」キーを押すと、[r]
そのスクリプトでゲームがスタートします。[l][r]
バージョンはティラノスクリプトV461です。[l][r]
荻原制作のプラグインのほぼすべてがここで読み込めます。